api_public_register:
  controller: App\Controller\AuthController::register
  path: api/register
  methods: POST

api_login_check:
  path: api/login_check
  methods: POST

api_admin_login:
  path: api/admin_login
  methods: POST

api_get_users:
  controller: App\Controller\AuthController::getUsers
  path: api/users
  methods: GET

api_search_users:
  controller: App\Controller\AuthController::searchUsers
  path: api/users/search

api_public_getCards:
  controller: App\Controller\CardController::getCards
  path: /cards
  methods: GET

api_public_searchCards:
  controller: App\Controller\CardController::searchCards
  path: /cards/search
  methods: GET

api_public_addCard:
  controller: App\Controller\CardController::addCard
  path: card/new
  methods: POST

api_public_showCard:
  controller: App\Controller\CardController::showCard
  path: card/{id}
  methods: GET

api_public_editCard:
  controller: App\Controller\CardController::editCard
  path: card/{id}/edit
  methods: PUT

api_public_deleteCard:
  controller: App\Controller\CardController::deleteCard
  path: card/{id}
  methods: DELETE

