api_public_register:
  controller: App\Controller\AuthController::register
  path: /register
  methods: POST

api_login_check:
  path: api/login_check
  methods: POST

api_admin_login:
  path: api/admin_login
  methods: POST

