framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            kafka:
                dsn: '%env(KAFKA_DSN)%'
                options:
                    topic:
                        name: 'baseball_cards_topic'
                    kafka_conf:
                        metadata.broker.list: 'host.docker.internal:9092'
        routing:
            'App\Message\BaseballCardMessage': kafka

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
